name: Build iOS IPA
on: [push]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Use v4 (Latest)
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Build IPA (No Signing)
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          
      - name: Upload IPA
        # UPDATED TO v4 (This fixes your error)
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ios-app
          path: build/ios/iphoneos/Runner.ipa
